### ISSUE TITLE
Truncation of response body

### ISSUE THREAD

**Issue by Shardj** [Codeception/module-phpbrowser#8]
https://github.com/guzzle/guzzle/issues/1610

Easily fixable, inside createResponse() of Guzzle.php the line of code `$body = (string) $response->getBody();` exists. This is causing streams of size greater than the default response to be truncated. In my case it's causing my seeResponseIsJson() assertion to fail as the end of my json string is being cut off.

The stream needs to be read from in a loop such as the example below which @Servuc provided in the above linked issue. 

```
$body = $response->getBody();
while (!$body->eof()) {
    echo $body->read(1024);
}
```

**Comment by Naktibalda** [comment]
My bad, it was limitation of httpbin.org

I tested with 50M response and `grabPageSource` returned entire response.
